AllCops:
  NewCops: enable
GlobalVars:
  AllowedVariables:
    - $config
    - $logger
Layout/LineLength:
  Max: 160
Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Lint/UnderscorePrefixedVariableName:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/AbcSize:
  Max: 18
Style/FrozenStringLiteralComment:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
Style/StringLiterals:
  EnforcedStyle: double_quotes
