AllCops:
  NewCops: enable
GlobalVars:
  AllowedVariables:
    - $config
    - $logger
Style/Documentation:
  Enabled: false
Lint/UnderscorePrefixedVariableName:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
Style/StringLiterals:
  EnforcedStyle: double_quotes
