AllCops:
  NewCops: enable
GlobalVars:
  AllowedVariables:
    - $config
Style/FrozenStringLiteralComment:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
Style/StringLiterals:
  EnforcedStyle: double_quotes
