name: Docker Image CI

on:
  push:
    branches:
      - '**'
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_NAME: kaiten-bot
  DOCKER_REGISTRY: asia-northeast1-docker.pkg.dev

jobs:

  build:

    runs-on: ubuntu-latest
    environment: CI

    steps:
    - uses: actions/checkout@v3

    - name: Auth GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: test
      run: echo $DOCKER_REGISTRY/$PROJECT_ID/$SERVICE_NAME/console:${{ github.sha }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Authorize Docker push
      run: gcloud auth configure-docker $DOCKER_REGISTRY

    - name: Docker Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: docker/console/Dockerfile
        tags: $DOCKER_REGISTRY/$PROJECT_ID/$SERVICE_NAME/console:${{ github.sha }}
        push: false
