name: Docker Image CI

on:
  push:
    branches:
      - '**'
env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  SERVICE_NAME: kaiten-bot

jobs:

  build:

    runs-on: ubuntu-latest
    environment: CI

    steps:
    - uses: actions/checkout@v3

    - name: Auth GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Authorize Docker push
      run: gcloud auth configure-docker

    - name: Build Docker image
      run: docker build -f docker/console/Dockerfile -t asia-northeast1-docker.pkg.dev/$PROJECT_ID/$SERVICE_NAME/console:${{ github.sha }} .

    - name: Push Docker Image
      run: docker push asia-northeast1-docker.pkg.dev/$PROJECT_ID/$SERVICE_NAME/console:${{ github.sha }}
