name: Docker Image CI

on:
  push:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: google-github-actions/auth@v0
      with:
        credentials_json: "${{ secrets.GCP_SA_KEY }}"
    - name: Build the Docker image
      run: docker build . -f docker/console/Dockerfile -t kaiten-bot/console:${{ github.sha }}
