name: Docker Image CI

on:
  push:
    branches:
      - '**'
env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}

jobs:

  build:

    runs-on: ubuntu-latest
    environment: CI

    steps:
    - uses: actions/checkout@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Auth GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Use gcloud CLI
      run: gcloud info

    - name: Build the Docker image
      run: docker build . -f docker/console/Dockerfile -t kaiten-bot/console:${{ github.sha }}
