name: Docker Image CI

on:
  push:
    branches:
      - '**'
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_NAME: kaiten-bot
  DOCKER_REGISTRY: asia-northeast1-docker.pkg.dev

jobs:

  build:

    runs-on: ubuntu-latest
    environment: CI

    steps:
    - uses: actions/checkout@v3

    - id: auth
      name: Auth GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}
        token_format: access_token
        cleanup_credentials: true

    - name: Login to Artifact Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.DOCKER_REGISTRY }}
        username: oauth2accesstoken
        password: ${{ steps.auth.outputs.access_token }}

    - name: Docker Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: docker/ruby/Dockerfile
        tags: |
          ${{ env.DOCKER_REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}/ruby:${{ github.sha }}
          ${{ env.DOCKER_REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}/ruby:latest
        push: true
