name: Docker Image CI

on:
  push:
    branches:
      - '**'
env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: test
      run: echo ${{ secrets.GCP_CREDENTIALS }}
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}
    - name: Build the Docker image
      run: docker build . -f docker/console/Dockerfile -t kaiten-bot/console:${{ github.sha }}
